### PR TITLE
Update the Stache tutorial

### PR DESCRIPTION
**Pull request by jpvillaisaza**
- s/has not/doesn't have
- s/indend/intend

### CODE REVIEW

**Comment by jpvillaisaza** [comment]
@mrkkrp I fixed two more things in this pull request. We can merge tomorrow and then push to production on Wednesday.

@jsl @mrkkrp Here's the link if you want to take a look on staging: https://staging.stackbuilders.com/tutorials/haskell/mustache-templates/

**Comment by mrkkrp** [comment]
@jpvillaisaza I also updated versions of libraries. It's better to show the latest version. (Nightly is used in `stack.yaml` because LTS does not support GHC 8 yet, but Template Haskell helpers need GHC 8, on the other hand we have field named `lts` in tutorials, so I put `lts-6.11` there — the newest LTS release.)

**Comment by mrkkrp** [comment]
I think we can merge now.

**Comment by jpvillaisaza** [comment]
@mrkkrp We can omit the `lts` field and add a `nightly` one instead. The tutorial template checks both.

**Comment by mrkkrp** [comment]
@jpvillaisaza Amended.

**Pull request merged**
