### PR TITLE
Generate tutorial feeds (also remove junk)

### PR DESCRIPTION
**Pull request by mrkkrp**
What about actual links to the feeds? Any idea on placement?

### CODE REVIEW

**Comment by mrkkrp** [comment]
Related to #37.

**Comment by juanpaucar** [comment]
Great Mark, thanks a lot. I also think it's worth to add actual links for the posts

**Comment by mrkkrp** [comment]
I added the links just now, they are in `archive.html` file.

**Review by juanpaucar — APPROVED** [review]

**Comment by juanpaucar** [comment]
@mrkkrp  LGTM. I totally forgot about this PR. I there something else we need to merge it then?

**Comment by mrkkrp** [comment]
Nope, I think it should be OK in its present state. Merging.

**Pull request merged**
